DressUpWeb/DressUpWeb/Controllers/ProductController.cs
using DressUp.Services.Data.Interfaces;
using DressUp.Services.Data.Models.Product;
using DressUp.Web.Infrastructure.Extensions;
using DressUp.Web.ViewModels.Product;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static DressUp.Common.NotificationMessagesConstants;

namespace DressUp.Web.Controllers;


public class ProductController : BaseController
{
	private readonly IProductService productService;
	private readonly IFavoriteService favoriteService;
	private readonly IBrandService brandService;
	private readonly ICategoryService categoryService;

	public ProductController(
		IProductService productService,
		IFavoriteService favoriteService,
		IBrandService brandService,
		ICategoryService categoryService)
	{
		this.productService = productService;
		this.favoriteService = favoriteService;
		this.brandService = brandService;
		this.categoryService = categoryService;
	}

	[HttpGet]
	[AllowAnonymous]
	// Show All products with QueryModel for pagination
	public async Task<IActionResult> All([FromQuery] AllProductsQueryModel queryModel)
	{
		try
		{
			AllProductsFilteredAndPagedServiceModel serviceModel = await productService.AllAsync(queryModel);

			queryModel.Products = serviceModel.Products;
			queryModel.TotalProducts = serviceModel.TotalProductsCount;
			queryModel.Categories = await categoryService.GetCategoriesNamesAsync();
			queryModel.Brands = await brandService.GetBrandsNameAsync();
			queryModel.SizeTypes = productService.GetAllSizeTypes();

			return View(queryModel);
		}
		catch
		{
			return GeneralError();
		}
	}


	// Add product to favorite
	public async Task<IActionResult> AddToFavorite(int productId)
	{
		try
		{
			bool isProductExist = await productService.IsProductExistByIdAsync(productId);
			if (!isProductExist)
			{
				TempData[ErrorMessage] = ErrorMessages.InvalidProductToFavorite;
				return NotFound();
			}

			bool isProductFavorite = await productService.IsProductFavorite(User.GetId(), productId);
			if (isProductFavorite)
			{
				TempData[ErrorMessage] = ErrorMessages.AlreadyAddedToFavorite;
				return BadRequest();
			}

			await favoriteService.AddToFavoriteAsync(productId, User.GetId());
			TempData[SuccessMessage] = SuccessMessages.AddedToFavorite;
			return RedirectToAction(nameof(All));
		}
		catch
		{
			return GeneralError();
		}
	}

	public async Task<IActionResult> RemoveFromFavorite(int productId)
	{
		if (!User.Identity?.IsAuthenticated ?? false)
		{
			TempData[ErrorMessage] = ErrorMessages.YouMustLogedInToRemoveFavorite;
			return RedirectToAction(nameof(All));
		}

		try
		{
			bool isProductExist = await productService.IsProductExistByIdAsync(productId);
			if (!isProductExist)
			{
				TempData[ErrorMessage] = ErrorMessages.InvalidProductToFavorite;
				return NotFound();
			}

			bool isProductFavorite = await productService.IsProductFavorite(User.GetId(), productId);
			if (!isProductFavorite)
			{
				TempData[ErrorMessage] = ErrorMessages.InvalidProductToRemoveFromFavorite;
				return BadRequest();
			}

			await favoriteService.RemoveFromFavoriteAsync(productId, User.GetId());
			TempData[SuccessMessage] = SuccessMessages.RemovedFromFavorite;
			return RedirectToAction(nameof(Favorite));
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpGet]
	// Show Favoritre products with QueryModel for pagination
	public async Task<IActionResult> Favorite([FromQuery] AllProductsQueryModel queryModel)
	{
		try
		{
			AllProductsFilteredAndPagedServiceModel serviceModel =
				await favoriteService.AllFavoritesAsync(queryModel, User.GetId());

			queryModel.Products = serviceModel.Products;
			queryModel.TotalProducts = serviceModel.TotalProductsCount;
			queryModel.Categories = await categoryService.GetCategoriesNamesAsync();
			queryModel.Brands = await brandService.GetBrandsNameAsync();
			queryModel.SizeTypes = productService.GetAllSizeTypes();

			return View(queryModel);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpGet]
	public async Task<IActionResult> Add()
	{
		// Only Admin can Add product
		bool isModer = User.IsModerator();
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToAddProduct;
			return Unauthorized();
		}

		try
		{
			ProductFormModel formModel = new()
			{
				Brands = await brandService.GetAllBrandsAsync(),
				Categories = await categoryService.GetAllCategoriesAsync(),
				SizeTypes = productService.GetAllSizeTypes()
			};

			return View(formModel);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpPost]
	public async Task<IActionResult> Add(ProductFormModel formModel, IEnumerable<IFormFile> files)
	{
		if (!ModelState.IsValid)
		{
			return View(formModel);
		}

		// Only Admin can Add product
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToAddProduct;
			return Unauthorized();
		}

		try
		{
			// Save uploaded image in wwwroot
			IEnumerable<string> uploadedFiles;
			if (files != null)
			{
				uploadedFiles = productService.UploadImages(files, formModel.SizeType);
				// Add ImageLinks to form model
				foreach (string imgUrl in uploadedFiles)
				{
					formModel.Images.Add(new ProductImagesViewModel
					{
						ImageUrl = imgUrl,
					});
				}
			}

			await productService.AddProductAsync(formModel);

			TempData[SuccessMessage] = SuccessMessages.AddedProduct;
			return RedirectToAction(nameof(All));
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpGet]
	public async Task<IActionResult> Edit(int id)
	{
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToEdit;
			return Unauthorized();
		}

		try
		{
			bool isProductExist = await productService.IsProductExistByIdAsync(id);
			if (!isProductExist)
			{
				TempData[ErrorMessage] = ErrorMessages.ProductDoesNotExist;
				return NotFound();
			}

			ProductFormModel formModel = await productService.GetProductByIdAsync(id);

			formModel.Brands = await brandService.GetAllBrandsAsync();
			formModel.Categories = await categoryService.GetAllCategoriesAsync();
			formModel.SizeTypes = productService.GetAllSizeTypes();

			return View(formModel);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpPost]
	public async Task<IActionResult> Edit(ProductFormModel formModel, int id)
	{

		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToEdit;
			return Unauthorized();
		}

		if (!ModelState.IsValid)
		{
			return View(formModel);
		}

		try
		{
			formModel.Brands = await brandService.GetAllBrandsAsync();
			formModel.Categories = await categoryService.GetAllCategoriesAsync();
			formModel.SizeTypes = productService.GetAllSizeTypes();

			await productService.EditProductAsync(formModel, id);
			TempData[SuccessMessage] = SuccessMessages.EditedProduct;
			return RedirectToAction(nameof(All));
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpGet]
	[AllowAnonymous]
	public async Task<IActionResult> Details(int id, string information)
	{
		try
		{
			bool isProductExist = await productService.IsProductExistByIdAsync(id);
			if (!isProductExist)
			{
				TempData[ErrorMessage] = ErrorMessages.ProductDoesNotExist;
				return NotFound();
			}

			ProductDetailsViewModel model = await productService.GetProductDetailsByIdAsync(id);

			if (model.GetUrlInformation() != information)
			{
				return NotFound();
			}

			return View(model);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpGet]
	public async Task<IActionResult> Delete(int id)
	{
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToDelete;
			return Unauthorized();
		}

		try
		{
			bool isProductExist = await productService.IsProductExistByIdAsync(id);
			if (!isProductExist)
			{
				TempData[ErrorMessage] = ErrorMessages.ProductDoesNotExist;
				return NotFound();
			}

			ProductPreDeleteDetails model = await productService.GetProductPreDeleteDetailsByIdAsync(id);
			return View(model);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpPost]
	public async Task<IActionResult> Delete(ProductPreDeleteDetails model, int id)
	{
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToDelete;
			return Unauthorized();
		}

		try
		{
			bool isProductExist = await productService.IsProductExistByIdAsync(id);
			if (!isProductExist)
			{
				TempData[ErrorMessage] = ErrorMessages.ProductDoesNotExist;
				return NotFound();
			}

			await productService.DeleteProductByIdAsync(id);
			TempData[WarningMessage] = WarningMessages.ProductDeletedSuccessfuly;
		}
		catch
		{
			return GeneralError();
		}

		return RedirectToAction(nameof(All));
	}

	private IActionResult GeneralError()
	{
		TempData[ErrorMessage] = ErrorMessages.UnexpextedError;

		return RedirectToAction("Index", "Home");
	}

}

DressUpWeb/DressUpWeb/Controllers/StoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using DressUp.Web.ViewModels.Store;
using DressUp.Services.Data.Interfaces;
using DressUp.Services.Data.Models.Store;
using DressUp.Web.Infrastructure.Extensions;
using static DressUp.Common.NotificationMessagesConstants;

namespace DressUp.Web.Controllers;

public class StoreController : BaseController
{
	private readonly IStoreService storeService;
	private readonly IAddressService addressService;

	public StoreController(
		IStoreService storeService,
		IAddressService addressService)
	{
		this.storeService = storeService;
		this.addressService = addressService;
	}



	[HttpGet]
	[AllowAnonymous]
	public async Task<IActionResult> All([FromQuery] AllStoresQueryModel queryModel)
	{
		try
		{
			AllStoresFilteredAndPagedServiceModel serviceModel = await storeService.AllStoresAsync(queryModel);

			queryModel.Stores = serviceModel.Stores;
			queryModel.TotalStores = serviceModel.TotalStoresCount;
			queryModel.StoreStatuses = storeService.GetAllStoreStatus();

			return View(queryModel);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpGet]
	[AllowAnonymous]
	public async Task<IActionResult> Details(int id)
	{
		try
		{
			if (!await storeService.IsStoreExistByIdAsync(id))
			{
				TempData[ErrorMessage] = ErrorMessages.StoreDoesNotExist;
				return NotFound();
			}

			StoreDetailsViewModel viewModel = await storeService.GetStoreDetailsAsyncById(id);
			return View(viewModel);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpGet]
	public async Task<IActionResult> Add()
	{
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToAddStore;
			return Unauthorized();
		}

		try
		{
			StoreFormModel model = new();
			model.AddressForm = new()
			{
				Cities = await addressService.GetAllCitiesAsync(),
				Countries = await addressService.GetAllCountriesAsync(),
			};

			return View(model);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpPost]
	public async Task<IActionResult> Add(StoreFormModel formModel)
	{
		if (!ModelState.IsValid)
		{
			formModel.AddressForm.Cities = await addressService.GetAllCitiesAsync();
			formModel.AddressForm.Countries = await addressService.GetAllCountriesAsync();

			return View(formModel);
		}

		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToAddStore;
			return Unauthorized();
		}

		try
		{
			if (!await addressService.IsCityExistByIdAsync(formModel.AddressForm.CityId))
			{
				TempData[ErrorMessage] = ErrorMessages.CityDoesNotExist;

				formModel.AddressForm.Cities = await addressService.GetAllCitiesAsync();
				formModel.AddressForm.Countries = await addressService.GetAllCountriesAsync();

				return View(formModel);
			}

			if (!await addressService.IsCountryExistByIdAsync(formModel.AddressForm.CountryId))
			{
				TempData[ErrorMessage] = ErrorMessages.CountryDoesNotExist;

				formModel.AddressForm.Cities = await addressService.GetAllCitiesAsync();
				formModel.AddressForm.Countries = await addressService.GetAllCountriesAsync();

				return View(formModel);
			}

			await storeService.AddStoreAsync(formModel);
			TempData[SuccessMessage] = SuccessMessages.AddedStore;
		}
		catch
		{
			return GeneralError();
		}

		return RedirectToAction(nameof(All));
	}

	[HttpGet]
	public async Task<IActionResult> Edit(int id)
	{
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToEditStore;
			return Unauthorized();
		}

		try
		{
			if (!await storeService.IsStoreExistByIdAsync(id))
			{
				TempData[ErrorMessage] = ErrorMessages.StoreDoesNotExist;
				return NotFound();
			}

			StoreFormModel formModel = await storeService.GetStoreByIdAsync(id);
			formModel.AddressForm.Cities = await addressService.GetAllCitiesAsync();
			formModel.AddressForm.Countries = await addressService.GetAllCountriesAsync();

			return View(formModel);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpPost]
	public async Task<IActionResult> Edit(StoreFormModel formModel, int id)
	{
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToEditStore;
			return Unauthorized();
		}

		if (!ModelState.IsValid)
		{
			formModel.AddressForm.Cities = await addressService.GetAllCitiesAsync();
			formModel.AddressForm.Countries = await addressService.GetAllCountriesAsync();
			return View(formModel);
		}

		try
		{
			if (!await storeService.IsStoreExistByIdAsync(id))
			{
				TempData[ErrorMessage] = ErrorMessages.StoreDoesNotExist;
				return NotFound();
			}

			await storeService.EditStoreAsync(formModel, id);
			TempData[SuccessMessage] = string.Format(SuccessMessages.EditedStore, formModel.Name);
			return RedirectToAction(nameof(All));
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpGet]
	public async Task<IActionResult> Delete(int id)
	{
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToEditStore;
			return Unauthorized();
		}

		try
		{
			if (!await storeService.IsStoreExistByIdAsync(id))
			{
				TempData[ErrorMessage] = ErrorMessages.StoreDoesNotExist;
				return NotFound();
			}

			StorePreDeleteDetails formModel = await storeService.GetProductPreDeleteDetailsByIdAsync(id);

			return View(formModel);
		}
		catch
		{
			return GeneralError();
		}
	}

	[HttpPost]
	public async Task<IActionResult> Delete(StorePreDeleteDetails formModel, int id)
	{
		if (!User.IsAdmin() && !User.IsModerator())
		{
			TempData[ErrorMessage] = ErrorMessages.AdminOrModeratorToEditStore;
			return Unauthorized();
		}

		try
		{
			if (!await storeService.IsStoreExistByIdAsync(id))
			{
				TempData[ErrorMessage] = ErrorMessages.StoreDoesNotExist;
				return NotFound();
			}

			await storeService.DeleteStoreByIdAsync(id);
			TempData[WarningMessage] = WarningMessages.DeletedStore;
			return RedirectToAction(nameof(All));
		}
		catch
		{
			return GeneralError();
		}
	}

	private IActionResult GeneralError()
	{
		TempData[ErrorMessage] = ErrorMessages.UnexpextedError;

		return RedirectToAction("Index", "Home");
	}
}

DressUpWeb/DressUpWeb/Views/Shared/_Layout.cshtml
@using DressUp.Data.Models.Enums
@using static DressUp.Common.GeneralApplicationConstants;

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - DressUpWeb</title>
	<link rel="stylesheet" href="https://bootswatch.com/5/sketchy/bootstrap.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/DressUpWeb.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />


</head>

<body>
	<header>

		<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
			<div class="container-fluid">
				<a class="navbar-brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">DressUp</a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarColor03">
					<ul class="navbar-nav me-auto">

						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Stores</a>
							<div class="dropdown-menu">
								@if (User.IsAdmin() || User.IsModerator())
								{
									<a class="dropdown-item" asp-area="" asp-controller="Store" asp-action="Add">Add Store</a>
									<div class="dropdown-divider"></div>
								}
								<a class="dropdown-item" asp-area="" asp-controller="Store" asp-action="All">All Stores</a>
							</div>
						</li>

						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dress for</a>
							<div class="dropdown-menu">
								@if (User.IsAdmin() || User.IsModerator())
								{
									<a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Add">Add product</a>
								}
								else
								{
									<a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="All" asp-route-sizeType="@SizeType.Women">Women</a>
									<a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="All" asp-route-sizeType="@SizeType.Men">Men</a>
									<a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="All" asp-route-sizeType="@SizeType.Child">Child</a>
								}
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="All">All Products</a>

							</div>
						</li>

						@if (User.Identity?.IsAuthenticated ?? false)
						{
							<li class="nav-item">
								<a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Favorite">Favorite products</a>
							</li>
						}
					</ul>
				</div>
				<partial name="_LoginPartial" />
			</div>
		</nav>
	</header>

	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; DressUp @ReleaseYear
			@if (DateTime.UtcNow.Year > ReleaseYear)
			{
				@Html.Raw($" - {@DateTime.UtcNow.Year}")
				;
			}

		</div>
	</footer>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/js/toastr.js"></script>
	<script src="~/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<partial name="_NotificationsPartial" />
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DressUpWeb/DressUpWeb/Views/Shared/_NotificationsPartial.cshtml
@using static DressUp.Common.NotificationMessagesConstants

@if (TempData.ContainsKey(ErrorMessage))
{
    <script>toastr.error('@TempData[ErrorMessage]');</script>
}

@if (TempData.ContainsKey(WarningMessage))
{
    <script>toastr.warning('@TempData[WarningMessage]');</script>
}

@if (TempData.ContainsKey(InformationMessage))
{
    <script>toastr.info('@TempData[InformationMessage]');</script>
}

@if (TempData.ContainsKey(SuccessMessage))
{
    <script>toastr.success('@TempData[SuccessMessage]');</script>
}

DressUpWeb/DressUpWeb/Views/Shared/_ProductFormPartial.cshtml
@model ProductFormModel
@{
	string? addAction = ViewData["AddAction"] as string;
}
<div class="row">
	<div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
		<form method="post" enctype="multipart/form-data" asp-controller="Product">
			<div class="form-group">
				<label asp-for="Name">Name</label>
				<input asp-for="Name" class="form-control" placeholder="Title..." />
				<span asp-validation-for="Name" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Description"></label>
				<textarea asp-for="Description" rows="4" class="form-control" placeholder="Very confortable summer dress..."></textarea>
				<span asp-validation-for="Description" class="small text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="BrandId"></label>
				<select asp-for="BrandId" class="form-control">
					<option value="">Choose your brand</option>
					@foreach (var brand in Model.Brands)
					{
						<option value="@brand.Id">@brand.Name</option>
					}
				</select>
				<span asp-validation-for="BrandId" class="small text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="CategoryId"></label>
				<select asp-for="CategoryId" class="form-control">
					<option value="">Choose your category</option>
					@foreach (var category in Model.Categories)
					{
						<option value="@category.Id">@category.Name</option>
					}
				</select>
				<span asp-validation-for="CategoryId" class="small text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="SizeType"></label>
				<select asp-for="SizeType" class="form-control">
					@foreach (var sizeType in Model.SizeTypes)
					{
						<option value="@sizeType">@sizeType</option>
					}
				</select>
				<span asp-validation-for="SizeType" class="small text-danger"></span>
			</div>

			<div class="form-group">
				<label asp-for="Price"></label>
				<input asp-for="Price" class="form-control">
				<span asp-validation-for="Price" class="small text-danger"></span>
			</div>


			<div class="form-group">
				<label asp-for="Quantity"></label>
				<input asp-for="Quantity" class="form-control">
				<span asp-validation-for="Quantity" class="small text-danger"></span>
			</div>

			@if (addAction != null && addAction == "Add")
			{
				<div class="form-group">
					<label>Upload Image</label>
					<input class="form-control" name="files" multiple="multiple" type="file" />
				</div>
			}

			<div class="text-center">
				<input class="btn btn-success mb-2 mt-2 w-100 p-3 fw-bold" type="submit" value="Save" />
				<a asp-action="All" class="btn btn-secondary mb-1 w-100 p-3 fw-bold">Return to All Products</a>
			</div>
		</form>
	</div>
</div>

DressUpWeb/DressUpWeb/Views/Shared/_ProductPartial.cshtml
@using DressUp.Services.Data.Interfaces
@using DressUp.Web.Infrastructure.Extensions
@model AllProductsViewModel

@inject IProductService ProductService

@{
	bool isProductFavorite = false;
	if (User.Identity?.IsAuthenticated ?? false)
	{
		isProductFavorite = await ProductService.IsProductFavorite(User.GetId(), Model.Id);
	}
}

<div class="col-md-4">
	<div class="card mb-3">
		<div class="card-body text-center">
			@if (Model.Images.Any())
			{
				<img class="card-img-top" src="@Url.Content(Model.Images.First().ImageUrl)" alt="@Model.Name Image">
			}
			else
			{
				<img class="card-img-top" src="~/DressPics/ImageCommingSoon.jpg" alt="Coming Soon Image">
			}
			<h4>@Model.Name</h4>
			<h6>Brand: <b>@Model.Brand</b></h6>
			<h6>Category: <b>@Model.Category</b></h6>
			<h6>
				Price:
				<b>@($"{Model.Price:f2}") BGN</b>
			</h6>
			<h6>(@(Model.Quantity > 0 ? "Quantity: " + Model.Quantity : "Product is unvaliable"))</h6>
			<br />
			<a asp-area="" asp-controller="Product" asp-action="Details" asp-route-id="@Model.Id" asp-route-information="@Model.GetUrlInformation()"
			   class="btn btn-success">Details</a>



			@if (User.Identity?.IsAuthenticated ?? false)
			{
				if (User.IsAdmin() || User.IsModerator())
				{
					<a asp-area="" asp-controller="Product" asp-action="Edit" asp-route-id="@Model.Id"
					   class="btn btn-warning">Edit</a>
					<a asp-area="" asp-controller="Product" asp-action="Delete" asp-route-id="@Model.Id"
					   class="btn btn-danger">Delete</a>
				}

				if (isProductFavorite)
				{
					<a asp-area="" asp-controller="Product" asp-action="RemoveFromFavorite" asp-route-productId="@Model.Id"
					   class="btn btn-success">Remove from favorite</a>
				}
				else
				{
					<a asp-area="" asp-controller="Product" asp-action="AddToFavorite" asp-route-productId="@Model.Id"
					   class="btn btn-success">Add to favorite</a>
				}

				<p></p>

				@if (Model.Quantity > 0)
				{
					<form class="input-group-sm" asp-area="" asp-controller="Product"
						  asp-action="Order" asp-route-id="@Model.Id" method="post">
						<input class="btn btn-primary" type="submit" value="Order" />
					</form>
				}
			}
		</div>
	</div>
</div>

DressUpWeb/DressUpWeb/Views/Shared/_StorePartial.cshtml
@using DressUp.Services.Data.Interfaces
@using DressUp.Web.Infrastructure.Extensions
@model AllStoresViewModel

<div class="col-md-4">
	<div class="card mb-3">
		<div class="card-body text-center">
			<img class="card-img-top" src="@Url.Content(Model.ImageUrl)" alt="@Model.Name Image">
			<h4>@Model.Name</h4>
			<h6>Opening Time: <b>@Model.OpeningTime.ToShortTimeString()</b></h6>
			<h6>Closing Time: <b>@Model.ClosingTime.ToShortTimeString()</b></h6>
			<h6>At the moment:
				@if (Model.Status == true)
				{
					<span class="text-success"><strong>Open</strong></span>
				}
				else
				{
					<span class="text-danger"><strong>Closed</strong></span>
				}
			</h6>

			<br />
			<a asp-area="" asp-controller="Store" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-success">Details</a>

			@if (User.IsAdmin() || User.IsModerator())
			{
				<a asp-area="" asp-controller="Store" asp-action="Edit" asp-route-id="@Model.Id"
				   class="btn btn-warning">Edit</a>
				<a asp-area="" asp-controller="Store" asp-action="Delete" asp-route-id="@Model.Id"
				   class="btn btn-danger">Delete</a>
				<p></p>
			}
		</div>
	</div>
</div>